[project]
name = "PDP"
version = "0.1.0"
description = "Physics Data Plotter (PDP)"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.3",
    "dearpygui",
    "numpy",
    "scipy",
    "pywin32",
    "pyinstaller"
]
