name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Install dependencies using uv sync
        run: uv sync

      - name: Verify packages installed by uv
        run: uv pip list

      - name: Check PyInstaller version
        run: .venv\Scripts\python.exe -m PyInstaller --version

      - name: Build executable with PyInstaller
        run: .venv\Scripts\python.exe -m PyInstaller --onefile --noconsole -n PDP main.py

      - name: List files in dist directory
        run: Get-ChildItem -Path dist -Recurse
        shell: pwsh
        if: always()

      - name: Compress executable
        run: |
          Compress-Archive -Path dist/PDP.exe -DestinationPath dist/PDP.zip
        shell: pwsh

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          artifacts: dist/PDP.zip
          allowUpdates: true
          generateReleaseNotes: true