name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v1

      - name: Install project dependencies using uv sync
        env:
          UV_NO_CREATE_VENV: "1"
        run: uv sync

      - name: Install PyInstaller using uv
        run: |
          uv pip install pyinstaller --system # PyInstaller also goes into system Python

      # Optional: Debug step to see where things are
      - name: List packages in system Python
        env:
          UV_NO_CREATE_VENV: "1"
        run: uv pip list
        shell: pwsh

      - name: Build executable with PyInstaller
        run: |
          python -m PyInstaller --onefile --noconsole -n PDP main.py # Now Python has both

      - name: Compress executable
        run: |
          Compress-Archive -Path dist/PDP.exe -DestinationPath dist/PDP.zip

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          artifacts: dist/PDP.zip
          allowUpdates: true
          generateReleaseNotes: true