name: Build and Release

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.3

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable
        run: |
          python -m PyInstaller --onefile --noconsole -n PDP main.py

      - name: Compress executable
        run: Compress-Archive -Path dist/PDP.exe -DestinationPath dist/PDP.zip

      - name: Create GitHub Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          artifacts: dist/PDP.zip
          allowUpdates: true
          generateReleaseNotes: true
