name: Build and Release PDP

on:
  push:
    tags:
      - 'v*'  # Only run on version tags like v1.0, v2.0 etc.

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # Match your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          python -m PyInstaller --onefile --noconsole -n PDP main.py

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/PDP.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
